CREATE TABLE IF NOT EXISTS mpa_ratings
(
    mpa_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_rating_name VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
 film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 film_name VARCHAR(60) NOT NULL,
 description VARCHAR(200),
 rate INTEGER,
 release_date DATE,
 duration INTEGER,
 mpa_rating_id INTEGER REFERENCES mpa_ratings (mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(60) NOT NULL,
    login VARCHAR(60),
    email VARCHAR(60) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT NOT NULL REFERENCES films (film_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id INTEGER NOT NULL REFERENCES films (film_id),
    genre_id INTEGER NOT NULL REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    request_user_id BIGINT NOT NULL REFERENCES users (user_id),
    accept_user_id BIGINT NOT NULL REFERENCES users (user_id),
    is_accepted BOOLEAN
);